### ISSUE TITLE
Problems with hotspots

### ISSUE THREAD

**Issue by geraseva** [RosettaCommons/protein_generator#23]
Running: 
```
python ./protein_generator/inference.py \
    --num_designs 1 \
    --out result/prot_gen_fold \
    --pdb 5KQVpart.pdb \
    --contigs 4-153,0 231-231,0 \
    --hotspots E88,E96,E64 \
    --T 25 --save_best_plddt \
    --dssp_pdb /content/7DET_B.pdb
```
raises: 
```
Traceback (most recent call last):
  File "/content/./protein_generator/inference.py", line 238, in <module>
    main()
  File "/content/./protein_generator/inference.py", line 235, in main
    S.generate_sample()
  File "/content/protein_generator/utils/sampler.py", line 814, in generate_sample
    self.setup()
  File "/content/protein_generator/utils/sampler.py", line 568, in setup
    self.make_hotspot_features()
  File "/content/protein_generator/utils/sampler.py", line 159, in make_hotspot_features
    for n,x in enumerate(self.features['mappings']['complex_con_ref_pdb_idx']):
KeyError: 'complex_con_ref_pdb_idx'
```

**Comment by geraseva** [comment]
My fault, should have used: 
```
--contigs A4-153,0 231-231 
```
